add_lunch_combo chroma_angler-userdebug
add_lunch_combo chroma_bullhead-userdebug
add_lunch_combo chroma_hammerhead-userdebug
add_lunch_combo chroma_mako-userdebug
add_lunch_combo chroma_shamu-user
add_lunch_combo chroma_sprout4-user
add_lunch_combo chroma_sprout8-user